services:
  data-ingestion:
    image: data-ingestion:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    environment:
      - AIRFLOW_UID=${UID}
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/scraper /opt/airflow/plugins /opt/airflow/vector_db /opt/airflow/scripts &&
      chmod -R 777 /opt/airflow &&
      airflow standalone
      "